### ISSUE TITLE
I'm not able to add a item without primary category?

### ISSUE THREAD

**Issue by patidarkishor777** [eBayDeveloper/eBay_APICall_CodeSamples#8]
Hi Frnds,

I'm using eBay api to manage my listing items, I am able to create item if I'm passing a primaryCategory but I  want to add items without passing a primaryCategory. I want eBay to auto pick a best matched category. 

Is this possible?

Thanks

**Comment by patidarkishor777** [comment]
Can I have the script info or the गीत repo if you have?

**Comment by vyeluri5** [comment]
No, I dont have access to those repos anymore. 

Try this way 

if (titles.contains(“category or sub-cat name”))  ex: Skincare - powder etc
{
	return “cateogryCode”;
}
else if (title.contains(“")) 
{
	return “cateogryCode”;
}

**Comment by patidarkishor777** [comment]
> There's a call in the Trading API named GetSuggestedCategories. I always use that call first, using the title of the product that I want to list as keywords. The call returns a list of compatible category IDs, with percentage accuracy. I pick the highest accuracy, get it's ID, then make the actual listing call using the ID of the category from the GetSuggestedCategories response.

Thanks, this is working for me..
